image: archlinux:latest

before_script:
  - pacman --noconfirm -Syyu
  - pacman --noconfirm --needed -S git vim zsh sudo
  - useradd -d /builds/{GITLAB_USER} -g users -M -N builder
  - chown -R builder:users ..

install:
  stage: build
  script:
    - sudo -H -i -u builder ./install.sh --all
