image: archlinux:latest

before_script:
  - ls -laFh && pwd
  - pacman --noconfirm -Syyu
  - pacman --noconfirm --needed -S git vim zsh sudo
  - useradd -m -G wheel -s /bin/zsh builder

install:
  stage: build
  script:
    - /bin/su -c "./install.sh --all" - builder
