image: archlinux:latest

before_script:
  - pacman --noconfirm --needed -Syyu git vim zsh sudo
  - useradd -m -G wheel -s /bin/zsh "$GITLAB_USER_LOGIN"
  - cat /etc/sudoers

install:
  stage: build
  script:
    - /bin/su -c "/builds/$GITLAB_USER_LOGIN/dotfiles/install.sh --dotfiles" - $GITLAB_USER_LOGIN
