image: archlinux:latest

before_script:
  - pacman --noconfirm --needed -Syyu git vim zsh

test:
  stage: test
  script:
    - su -c "/builds/$GITLAB_USER_LOGIN/dotfiles/install.sh --dotfiles" - nobody
