image: archlinux:latest

before_script:
  - ls -laFh && pwd
  - pacman --noconfirm -Syyu
  - pacman --noconfirm --needed -S git vim zsh sudo
  - useradd -m $GITLAB_USER_NAME

install:
  stage: build
  script:
    - /bin/su -c "/build/$GITLAB_USER_NAME/install.sh --all" - $GITLAB_USER_NAME
