image: archlinux:latest

before_script:
  - pacman --noconfirm --needed -Syyu base base-devel git vim zsh
  - useradd -m -G wheel -s /bin/zsh "$GITLAB_USER_LOGIN"
  - sed -i '/%wheel\sALL=(ALL)\sNOPASSWD:\sALL/s/^#\s//g' /etc/sudoers

test:
  stage: test
  script:
    - /bin/su -c "/builds/$GITLAB_USER_LOGIN/dotfiles/install.sh --dotfiles --aur-helper --packages --extra-packages -y" - $GITLAB_USER_LOGIN
    - vim -E -s -u "/builds/$GITLAB_USER_LOGIN/dotfiles/.vimrc" +PlugInstall +qa
