image: archlinux:latest

before_script:
  - pacman --noconfirm --needed -Syyu fakeroot strip git vim zsh sudo
  - useradd -m -G wheel -s /bin/zsh "$GITLAB_USER_LOGIN"
  - sed -i '/%wheel\sALL=(ALL)\sNOPASSWD:\sALL/s/^#\s//g' /etc/sudoers

test:
  stage: test
  script:
    - /bin/su -c "/builds/$GITLAB_USER_LOGIN/dotfiles/install.sh --all -y" - $GITLAB_USER_LOGIN
