#!/bin/sh

dmenu_themed() {
    dmenu -nb "#282A36" \
          -nf "#F8F8F2" \
          -sb "#FF5555" \
          -sf "#282A36" \
          -fn "Mono-12.5" \
          "$@"
}

OPTIONS="poweroff\nreboot\nsuspend"

systemctl "$(echo -e $OPTIONS | dmenu_themed -p "Power")"
