#!/usr/bin/bash

OPTIONS="poweroff\nreboot\nsuspend"

case "$(echo -e $OPTIONS | dmenu -p  "Power" \
                                 -nb "#282A36" \
                                 -nf "#F8F8F2" \
                                 -sb "#FF5555" \
                                 -sf "#282A36" \
                                 -fn "Mono-12.5")" in
    poweroff) exec systemctl poweroff;;
    reboot)   exec systemctl reboot;;
    suspend)  exec systemctl suspend;;
esac
