#!/bin/sh

dmenu_themed() {
    dmenu -nb "#282A36" \
          -nf "#F8F8F2" \
          -sb "#BFBFBF" \
          -sf "#282A36" \
          -fn "Mono-12.5" \
          "$@"
}

vm=$(vboxmanage list vms \
         | sed 's/"\(.*\)".*/\1/' \
         | dmenu_themed -l 25 -p "VirtualBox" -i)

[ -z "$vm" ] && exit 1

if [ -z "$1" ]; then
    type=$(echo -e "gui\nheadless" \
               | dmenu_themed -p "Select type")
else
    type=$1
fi

[ -z "$type" ] && exit 1

vboxmanage startvm --type "$type" "$vm"

[ "$?" = "1" ] && notify-send "VirtualBox" "$vm is already running"
