#!/bin/sh

dmenu_themed() {
    dmenu -nb "#282A36" \
          -nf "#F8F8F2" \
          -sb "#8BE9FD" \
          -sf "#282A36" \
          -fn "Lucida Grande-12" \
          "$@"
}

text=$(echo "$(xclip -o)" | dmenu_themed -p "Google Translate")

[ -z $text ] && exit 1

if [ -z "$1" ]; then
    languages=$(echo -e ":vi\n:en\n:ko" | \
                dmenu_themed -p "Select [SOURCE]:[TARGET] languages")
else
    languages=$1
fi

[ -z "$languages" ] && exit 1

notify-send "Translate" "$(trans --no-ansi "$languages" "$text")"
