#!/bin/bash

dmenu_themed() {
    dmenu -nb "#282A36" \
          -nf "#F8F8F2" \
          -sb "#8BE9FD" \
          -sf "#282A36" \
          -fn "Mono-12.5" \
          "$@"
}

text=$(dmenu_themed -p "Google Translate" <&-)

if [ -z $text ]; then
    exit 1
fi

languages=$(echo -e "en:vi\n:en\n:vi\n:ko" | \
            dmenu_themed -p "Select [SOURCE]:[TARGET] languages")

if [ -z $languages ]; then
    exit 1
fi

notify-send "Translate" "$(trans --no-ansi "$languages" "$text")"
