#!/bin/sh

dmenu_themed() {
    dmenu -nb "#282A36" \
          -nf "#F8F8F2" \
          -sb "#F1FA8C" \
          -sf "#282A36" \
          -fn "Mono-12.5" \
          "$@"
}

expression=$(dmenu_themed -p "Calculator" <&-)

if [ -z "$expression" ]; then
    exit 1
fi

result=$(echo "$expression" | bc -l | dmenu_themed -p "Result")

if [ -z "$result" ]; then
    exit 1
fi

echo -n "$result" | xclip -selection clipboard
