#!/bin/sh

cat ~/.config/sxhkd/sxhkdrc \
    | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' \
    | column -t -s $'\t' \
    | dmenu -p  "Key bindings" \
            -nb "#282A36" \
            -nf "#F8F8F2" \
            -sb "#FF79C6" \
            -sf "#282A36" \
            -fn "Mono-12.5" \
            -l  25
