[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "net"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"

[[block]]
block = "memory"

[[block]]
block = "sound"

[[block]]
block = "time"

[[block]]
block = "battery"
