#! /bin/sh

# Autostart
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
$HOME/.config/polybar/launch &
sxhkd &
xsetroot -cursor_name left_ptr &
fcitx &
compton &
xautolock -time 10 -locker i3lock-next &

# Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Border
bspc config border_width 1

# Gap
bspc config window_gap   20

# Color
bspc config normal_border_color   "#282A36"
bspc config focused_border_color  "#CAA9FA"
bspc config presel_feedback_color "#BD93F9"

# Monocule
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

# Float
bspc rule -a Lxappearance         state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a mpv                  state=floating
bspc rule -a Pcmanfm              state=floating
bspc rule -a Xarchiver            state=floating
bspc rule -a Zathura              state=tiled
